# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nvvm 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "nvvm"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["YuuShigetani"]
  s.date = "2017-12-24"
  s.description = "Neovim version manager."
  s.email = "s2g4t1n2@gmail.com"
  s.executables = ["nvvm"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".coveralls.yml",
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/nvvm",
    "etc/login",
    "lib/nvvm.rb",
    "lib/nvvm/accessor.rb",
    "lib/nvvm/cli.rb",
    "lib/nvvm/constants.rb",
    "lib/nvvm/ext/mkmf.rb",
    "lib/nvvm/installer.rb",
    "lib/nvvm/switcher.rb",
    "lib/nvvm/uninstaller.rb",
    "lib/nvvm/validator.rb",
    "lib/nvvm/version.rb",
    "nvvm.gemspec",
    "spec/accessor_spec.rb",
    "spec/installer_spec.rb",
    "spec/spec_helper.rb",
    "spec/switcher_spec.rb",
    "spec/uninstaller_spec.rb",
    "spec/validator_spec.rb",
    "spec/version_spec.rb"
  ]
  s.homepage = "http://github.com/calorie/nvvm"
  s.licenses = ["MIT"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9")
  s.rubygems_version = "2.5.1"
  s.summary = "Neovim version manager"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0.20.0"])
      s.add_development_dependency(%q<coveralls>, ["~> 0.7.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 6.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.52.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.15.1"])
    else
      s.add_dependency(%q<thor>, ["~> 0.20.0"])
      s.add_dependency(%q<coveralls>, ["~> 0.7.1"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rdoc>, ["~> 6.0"])
      s.add_dependency(%q<rspec>, ["~> 3.0"])
      s.add_dependency(%q<rubocop>, ["~> 0.52.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.15.1"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0.20.0"])
    s.add_dependency(%q<coveralls>, ["~> 0.7.1"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rdoc>, ["~> 6.0"])
    s.add_dependency(%q<rspec>, ["~> 3.0"])
    s.add_dependency(%q<rubocop>, ["~> 0.52.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.15.1"])
  end
end

